### ISSUE TITLE
Proposer aussi le livre en impression sur TheBookEditions.com ?

### ISSUE THREAD

**Issue by Naereen** [exo7math/python1-exo7#4]
Bonjour @arnbod,

Tout d'abord, :pray: un immense merci et :clap: :clap: un encore plus grand bravo, ce livre (et le second volume) sont des très bonnes ressources. Vraiment un très beau travail !  Et publier tout cela sous licence CC, c'est très généreux.

J'ai imprimé les livres moi-même, principalement parce que comme [beaucoup](https://reporterre.net/Quand-Extinction-Rebellion-demande-a-Jeff-Bezos-de-financer-sa-lutte-contre-Amazon), je boycotte Amazon.

> Le livre est en vente sur Amazon.fr à prix coûtant. Commander le livre sur Amazon.fr.

Est-ce que vous seriez d'accord de proposer aussi vos deux livres à la vente sur un autre site, plus éthique et moins critiquable écologiquement et socialement ?
Je pense notamment à [TheBookEditions.com](https://www.thebookedition.com/fr/), que @LaurentClaessens utilise depuis des années pour son incroyable livre [Le Frido](https://laurent.claessens-donadello.eu/frido.html).
Ce ne sera probablement pas plus cher que sur Amazon (et si ça l'est, on peut de nouveau se demander comment cette entreprise diabolique réussit à écraser ses concurrents), et [cette page](https://www.thebookedition.com/fr/calculer-prix-fabrication-livre) permet d'estimer le prix.

Merci d'avance; bien cordialement, Lilian Besson @Naereen

**Comment by Naereen** [comment]
Si vous êtes d'accord, mais que vous n'avez pas le temps, je peux le faire pour vous, ou au moins me renseigner davantage et présenter ici les détails que je trouverais.

**Comment by arnbod** [comment]
J'ai répondu par email.
