### ISSUE TITLE
Code issue in chapter Liste I in file code.pdf

### ISSUE THREAD

**Issue by RomainBdt** [exo7math/python1-exo7#5]
The code example in file code.pdf does not contain the correction of Chapter 7, Activity 2, exercice 3 and 4 and so on until the chapter 8. The code of Chapter7, Activity 2 exercice 1 and 2 is indeed copied 3 times in a row.
Issue is at page 42-45

**Comment by arnbod** [comment]
Thanks! It's corrected.
